# Generated by Django 5.2.8 on 2025-11-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='GameUser',
        ),
    ]
